language: node_js
node_js:
  - '12'
branches:
  only:
    - main
deploy:
  provider: heroku
  skip_cleanup: true
  on:
    branch: main
  api_key:
    secure: a//l+Xp3R0md3/N1CYs3fxm4zZcNB5GTwVNjmqKd/h1sduWFOgac5HlNa3Hxu6YnnAEYVDY6+Ql0qmBmulRe525A1mspJJ+LYtddQvz55FbkQzZjNKOoRYoKo+F5IuwY0lvhyeNmhCJny/znyNW9FJIBIWCwNnYA53BIu9XuRB7rOK1CotRU+H7f2mJ7+RgywvlPYF32HDIkp3pMUfoUvKTvJwVjxOJjHe2BXa7s8dAANh3WhZKnl7CoOk/G/ExIVoGK2/iEIjM+0cqDzCBYVsE+G/baHtqW979lJdqWwH+Bx0frFEmyWRWkNd1L23zZv4MjtH0dNE3uTy21erExPMqpK6Jw5ZEik0u5oASzHBc64YV1ut8SfNjHDhLkTfKAkHb8BQ9nFyEXbVSIvg+Ncnx8kol80XOQB4x7x8nq36Fna97v7WzAgaY+2Vi9vr/unO9DiRxfhXy7L9ZViQST1PzoQb7Dlty3GnV32b52mwRbUQk+B6ZitOFDa3sBag0U2TnzNE98JjDm3XyhrNYEFLUl2ADbulz/BpjRtl5I7anw9xzTC/HPBymjlw271oI4hY+bsS4Tt9HIATfMKw453NvNgpaHWiG6srCAmElE/VlAVPGiwz2BmF4F9wReMbx2fMjqIDmQyUTHWr0JgDYuQLJJL+jB76aEXl00iCnDkZQ=
  app: banking-nest-arias-upc-heroku
notifications:
  email:
    on_failure: change
    on_success: change
