language: node_js
node_js:
  - '12'
branches:
  only:
    - main
deploy:
  provider: heroku
  skip_cleanup: true
  on:
    branch: main
  api_key:
    secure: X2/hb289M2mRJ4rNB9XsRA6da6OzEF7vftkb6ETxuxa1/oVce35zq4S836+tnMScdHtu+IqXu1DyyRSUAlJoQzG9i+33WGRRgG5iiSWj5RNcLRKZi0RBtnbel4n9YKzWThhUwPcBiMFCaNmos+T+m7V+ZwxUXcaD0qzGQ0V50xFhGZ5hbJz8jN0Ehqg6RG6PNwZKVgyeg6+uZu0ihDwlX81pUbXI6bNW+lPMoQA7uDegJ98LZY58dOd4Mtz4e/UytYuzCIZPShzrSWEizDCGVsWFoyJhtHjPUOvaFxEh0fPGBSgYTkLNWDZni2YhoxNiDegJC/mg0koKIONLFXS5Cun6Cw0qkd09H1dH0hDvvD/tfsjkg55DGWv5p4F3FHbNvTFKU9+kJC0vXn2DBgF06WKzCLwDkFeB6uPml8fr5w4aCk3SHKBdjE7Rcnw3j+ZMYIDPk/cl2Njo+1yeqlEFvweWWNjBH/qaES9q/A6sovKBQyu4GFeq1kw25KImOgXNQBSbXx+VodBqxSEDwwBXyIy3GtgoJa7EkjrWYm/Vn3BHQz9Hwi3+xyhrbPqcG7azy2YYGJlKg/KEFKjgSoMpylznFCSOBbDqSdFLoa1zMlzvHGW4QBdBrX+s6YbpkR3gjEQYpOIvIrl/wSHF9tmqHYMSWahmOsZqskWbY4Bi0ts=
  app: banking-nest-arias-upc-heroku
notifications:
  email:
    on_failure: change
    on_success: change
