language: node_js
node_js:
  - '12'
branches:
  only:
    - main
deploy:
  provider: heroku
  skip_cleanup: true
  on:
    branch: main
  api_key:
    secure: ZUUgTrUXrogM8uW4IiO3qutm4ZExyR7P58jtxe40+Z7Pi/1qOuPwtj5NoA8zFOheDMDNi8vFV5Bx0ZBbjARtQlcA03Tb+rHCwHKDSYtlvPM3EedObGTrPHFUqtlK7pWAjUsdQGxj+WjETrsP/mF6oiceVC4osTWDOlH2ZCNSwSZjw7fyINXaCNxlIeqwFXgkxdXA2OcfUFc5gsmWy8WetXPQFntgk65T6Kjm6YnlQM8Y7/9tzrkJxGKGLTsu32zlTNWXW6pwFidTD/0Ld47sVXXPN1S+foGGc/rPKErFhhKpNesMdQheMfulwMBzukjKAJwdDO49RH6nT1Pw6ZaQNOW+fn8RPyvamv/xSShIcHiS668u+6wFqC8lpgD/dGcZwXD5V6B0QdCc7gYOMhqb4auLfrCsZwZ+XpkTVi+wksl+8OfPt07turjp6XuZSVkGlhqU2ivifwdZk7EV4+g3SdnfZY4ClvMJTsK6HGhWnoU78BfAxIi1+CVOF+RwrNASjmvCVbAsky4ftS+Ypqyu7cxwonSJIH4KGZLvANpu/f3LcDQdfEd/KYaHmZWR8dvXv3daNVu++oXA8HLBezG9cDHHiw4bqTSGrtvSv8/GvSjFIQ9h/9WfP0RoXA/ks8y3HLBNInw6TmQ00aKi5tr0RnjowIy3XJwfZr5SWnqXbiU=
  app: banking-nest-arias-upc-heroku
notifications:
  email:
    on_failure: change
    on_success: change
