language: node_js
node_js:
  - '12'
branches:
  only:
    - main
deploy:
  provider: heroku
  skip_cleanup: true
  on:
    branch: main
  api_key:
    secure: t763RN7PKMh1v6NIb3sCn9HAqw/2BeUfcQNDGc1Ks3aK0AbDmrtASnRQ0s4xJVmpHsmyfNW6bZE0Gm6Fm2KdStIA74uoh8omZcBHS6Hv/Mhil/mRvaY9GXcGekVS6iRvld2m4pDFsCDytpzOiChhNZS8Rxq/aBKfOvMM7UHuW+821hTodAS/umuhBoC1Nz8ZU+18KAmgVt2M14UohE5jRF9pLdqWvv2jIRLRYfXnOmP/ggONDlpZ4jBt7arTFb7EkXFL4nUOL35Vqs8l2n1wULXdUGIOiT2/5AVp5uiwUD0voEuculTgiQMdOQDQ3hnqa470oPsTWZYueUW34S8iDYvDNzU6Lhl5NEBGm1zksAQaBBTwRBkxeMHu+HcM/GpwaiJx+yPQw3R+gJNfnuWVBuiaRiNU0sXFN+eHZ65eJwyd3OxWRz7FIkTekonJkdImMw+EE8e/pCCKPM/QVo4wQeaS9CB4/6MXT52nIE0/q0wN9ZWIeD5CvsHtTiBfxmEQUZKYeS/SyBjHXtHMd5eWqz2+wi1m4nJH98W4RnxyioJqm1DxQopsX3fZk9D/g2Odt3+uOX8/EafVJB9vroQ9fxmTA8bT1c+UttMJl9S2ASY6m+sQw6wZp2+AOGLXXiFWYapaBpsOJRzGl+dDUajXQLZHr+W9XNO6EhzEXnLqA+U=
  app: banking-nest-arias-upc-heroku
notifications:
  email:
    on_failure: change
    on_success: change
