language: node_js
node_js:
  - '12'
branches:
  only:
    - master
deploy:
  provider: heroku
  skip_cleanup: true
  on:
    branch: master
  api_key:
    secure: I8gxP5AIfRUXg2nyC394S5Bz8QYVzOQFgzg71kcsDcvynXWV5/WoszTF6pAwUx6wsWfD1zN7iiU+jkC6pOCLzYn+ypvX3U94ec0HlkjgUpmak3b1hmJL9HUc6lkPa1vvsqc4iylNfElSuucWK9yh6c0hVMI/rh5uSc1AOXj0Huo+knvXsXF6zZPoHLdGLJ1ay26rMk+yEBJUYKm/1m+cGrBgLqjiMDQsxDhQ/rTGKCV0HL8EvMAXJo6+Mf75RBmI/zRqYOgNMXpsMwAil7xeDjXDIpyic7FLnWNJH9VzZb06k2/78oYz1W8Kn8PZ7ddbXeRjCDibQeEGcS4YA0giLr5q+TMFj4Lb7rnPkaPVf2AAbdbZ0czFP0pDtDw3B9rgqKnMy5zXvdW9yptDXLJrfkBiZ/X85rPO569vNhLxNvFb5DQekNMz45vj/PhWs8dkY6nvvmNWBKUYA1Odqc+YAEjlJboDyK7ZIFZSXmPHrq4N5MVPA/uyUIfR5vHt8D0DfxCjMJV73RQF1UCZM2YGelWITEFGuTQiZ3YfBlWlvmujYY+bRmjDQ0Dw28HXPkkp5aA1jlAoEliVSLSRNMz8cB7hkwBLeHLt7N7xUGGTIr6XsguEgRzXJmRYG3LUrIVev5fEZD+4sl6Tvx4+Ngzhfo5PqvEY6Wl9FdxsHg+duK0=
  app: banking-nest-upc-heroku
notifications:
  email:
    on_failure: change
    on_success: change
